# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FyLjwdVLWT8gjpzuQgPGTLrI7SZbAMuN
"""

my_list = [1, 2, 3, 4, 5]
total_sum = 0
for number in my_list:
    total_sum += number
print(f"The sum of the elements is: {total_sum}")

sentence = input("Enter a sentence: ")
length = len(sentence)
print(f"The length of the sentence is: {length} characters")
half_length = length // 2
first_half = sentence[:half_length]
print(f"The first half of the sentence is: {first_half}")

tuple_1 = (78, 45, 32, 19, 82, 77, 40, 39)
modified_list = list(tuple_1)
modified_list[2] = 100
modified_tuple = tuple(modified_list)
print(f"The modified tuple is: {modified_tuple}")

listA = [19, 32, 10, 55, 31, 32, 94, 29, 10, 65, 77, 40, 40]
listA.remove(32)
listA = [element for element in listA if element != 40]
del listA[5]
listA[9] = 300
listA.insert(2, 200)
print("Final List:", listA)
print("Length of the list:", len(listA))
print("Maximum value in the list:", max(listA))
print("Sum of all elements in the list:", sum(listA))

my_string = "The day has been long"
modified_string_a = my_string[:4] + my_string[5:]
modified_string_b = my_string * 4
modified_string_c = (my_string + '\n') * 3
modified_string_d = my_string[:7] + 'A' + my_string[8:]
modified_string_e = my_string[4:16]
print("Modified String (a):", modified_string_a)
print("Modified String (b):", modified_string_b)
print("Modified String (c):", modified_string_c)
print("Modified String (d):", modified_string_d)
print("Modified String (e):", modified_string_e)
print("Final String (f):", my_string)
print("Length of the final string:", len(my_string))