# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hMgmt7yldjRSemSemSZT_jWSGvkTnesa
"""

scores_input = input("Enter the scores separated by space: ")
scores = list(map(int, scores_input.split()))
unique_sorted_scores = sorted(set(scores), reverse=True)
if len(unique_sorted_scores) > 1:
    runner_up_score = unique_sorted_scores[1]
    print(f"The runner-up score is: {runner_up_score}")
else:
    print("There is no runner-up as there are not enough unique scores.")



D = {'John': [25, 32, 43], 'Peter': [87, 55, 96], 'Ram': [58, 55, 43], 'Meena': [63, 79, 85]}
name = input("Enter a name: ")
if name in D:
    D[name] = [88, 77, 99]
    print(f"Updated dictionary:\n{D}")
else:
    print("Name not found.")

age = int(input("Enter your age: "))
gender = input("Enter your gender (male/female): ")
if age < 5 or age > 60:
    ticket_price = 0
elif 5 <= age <= 12:
    ticket_price = 10
else:
    ticket_price = 50
if gender.lower() == "female":
    ticket_price *= 0.5
print(f"Ticket price: Rs.{ticket_price:.2f}")